version: '3.3'
services:
  web:
    build: .
    ports:
       - 5000:5000
    volumes:
      - .:/code
  mongodb_container:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: