version: '3.3'
services:
  web:
    build: .
    ports:
       - 5000:5000
    volumes:
      - .:/code
    depends_on:
      - neo
      - mongodb_container
  mongodb_container:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  neo:
        image: neo4j:latest
        ports: 
            - 7474:7474
            - 7687:7687
        volumes:
            - neo4j_data:/data/
        env_file:
            - .env.neo4j

volumes:
  mongodb_data_container:
  neo4j_data: